### ISSUE TITLE
Cannot run localhost:8000 php has error 500

### ISSUE THREAD

**Issue by fadakar** [vahiiiid/Laravel-Dockerized#1]
Hi, I install laravel with composer container and when docker-compose up server works fine but when sending a request to localhost:8000 PHP throw 500 error without any logs
how to enable PHP error logs?

please help me

**Comment by vahiiiid** [comment]
Hi
Have you checked your laravel.log file?
and if there is nothing there, maybe you should change debaug value into true in the .env file
finally if you can't find the logged error, you can have a try by seeing related container's log, php container especially
if you still have a problem let me know with more details

**Comment by fadakar** [comment]
There were no logs in the logs 
ENV. debug is true
I google it and I realized that PHP debug is off, how can turn on PHP errors in docker with Nginx and PHP FastCGI?
